name: .NET Tests

on:
  # Run on branch pushes
  push:
    branches: [ master ]
  # Run on pull requests
  pull_request:
  # Manual trigger
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: install reportgenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
    - name: coverlet
      uses: b3b00/coverlet-action@1.1.1
      with:
        testProject: 'PolloPollo.Repository.Tests/PolloPollo.Services.Tests.csproj'
        output: 'lcov.info'
        outputFormat: 'lcov'
    - name: coveralls
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        path-to-lcov: ${{steps.coverlet.outputs.coverageFile}}
