name: .NET Tests

on:
  # Run on branch pushes
  push:
    branches: [ master ]
  # Run on pull requests
  pull_request:
  # Manual trigger
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: coverlet
      uses: b3b00/coverlet-action@1.1.0
      with:
        testProject: 'PolloPollo.Repository.Tests/PolloPollo.Services.Tests.csproj'
        output: 'lcov.info'
        outputFormat: 'lcov'
    - name: coveralls
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        path-to-lcov: ${{steps.coverlet.outputs.coverageFile}}
